import { requestUrl } from "obsidian";
import type { AddressBook, CardDavResource, ContactSettings } from "./types";

export interface ParsedVCard { uid: string; displayName: string; givenName: string; familyName: string; emails: string[]; phones: string[]; organization: string; addresses: string[]; websites: string[]; birthday: string; notes: string; }
function unescape(value: string): string { return value.replace(/\\n/gi, "\n").replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\\\/g, "\\").trim(); }
function unfold(input: string): string[] { const lines = input.replace(/\r/g, "").split("\n"); const out: string[] = []; for (const line of lines) { if (/^[ \t]/.test(line) && out.length) out[out.length - 1] += line.slice(1); else out.push(line); } return out; }
export function parseVCard(input: string): ParsedVCard {
  const fields = new Map<string, string[]>();
  for (const line of unfold(input)) { const colon = line.indexOf(":"); if (colon < 0) continue; const key = line.slice(0, colon).split(";")[0].toUpperCase(); const value = unescape(line.slice(colon + 1)); fields.set(key, [...(fields.get(key) ?? []), value]); }
  const name = (fields.get("N")?.[0] ?? "").split(";"); const displayName = fields.get("FN")?.[0] ?? ([name[1], name[0]].filter(Boolean).join(" ") || "Unnamed contact");
  return { uid: fields.get("UID")?.[0] ?? "", displayName, givenName: name[1] ?? "", familyName: name[0] ?? "", emails: fields.get("EMAIL") ?? [], phones: [...(fields.get("TEL") ?? [])], organization: fields.get("ORG")?.[0] ?? "", addresses: fields.get("ADR") ?? [], websites: fields.get("URL") ?? [], birthday: fields.get("BDAY")?.[0] ?? "", notes: fields.get("NOTE")?.join("\n") ?? "" };
}
export function parseAddressBooks(xml: string, baseUrl: string): AddressBook[] { const result: AddressBook[] = []; const response = xml.match(/<[^>]*response[\s\S]*?<\/[^>]*response>/gi) ?? []; for (const chunk of response) { const href = chunk.match(/<[^>]*href[^>]*>([\s\S]*?)<\//i)?.[1]?.trim(); if (!href) continue; const label = chunk.match(/<[^>]*(?:displayname|addressbook-description)[^>]*>([\s\S]*?)<\//i)?.[1]?.replace(/<[^>]+>/g, "").trim() ?? href; result.push({ href: new URL(href, baseUrl).toString(), label }); } return [...new Map(result.map(item => [item.href, item])).values()]; }
export async function discoverAddressBooks(settings: ContactSettings): Promise<AddressBook[]> { if (!settings.carddavUrl.trim()) throw new Error("Enter the iCloud CardDAV discovery URL first."); const response = await requestUrl({ url: settings.carddavUrl, method: "REPORT", headers: authHeaders(settings), body: "<?xml version=\"1.0\"?><d:propfind xmlns:d=\"DAV:\" xmlns:card=\"urn:ietf:params:xml:ns:carddav\"><d:prop><d:displayname/><d:resourcetype/></d:prop></d:propfind>" }); return parseAddressBooks(response.text, settings.carddavUrl); }
export async function fetchResources(settings: ContactSettings): Promise<CardDavResource[]> { const url = settings.carddavAddressBookUrl || settings.carddavUrl; if (!url.trim()) throw new Error("Select an iCloud address book before syncing."); const response = await requestUrl({ url, method: "REPORT", headers: { ...authHeaders(settings), Accept: "application/xml, text/xml, text/vcard" }, body: "<?xml version=\"1.0\"?><c:addressbook-query xmlns:d=\"DAV:\" xmlns:c=\"urn:ietf:params:xml:ns:carddav\"><d:prop><d:getetag/><d:getcontenttype/><c:address-data/></d:prop></c:addressbook-query>" }); const resources: CardDavResource[] = []; const chunks = response.text.match(/<[^>]*response[\s\S]*?<\/[^>]*response>/gi) ?? []; for (const chunk of chunks) { const href = chunk.match(/<[^>]*href[^>]*>([\s\S]*?)<\//i)?.[1]?.trim(); const etag = chunk.match(/<[^>]*getetag[^>]*>([\s\S]*?)<\//i)?.[1]?.trim() ?? ""; const data = chunk.match(/<[^>]*address-data[^>]*>([\s\S]*?)<\//i)?.[1]; if (href && data) resources.push({ href: new URL(href, url).toString(), etag, vcardText: data.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&amp;/g, "&") }); } return resources; }
function authHeaders(settings: ContactSettings): Record<string, string> { const token = `${settings.username}:${settings.appPassword}`; return settings.username && settings.appPassword ? { Authorization: `Basic ${btoa(token)}` } : {}; }
