import { App, Modal, Notice, Setting, TFile } from "obsidian";
import type PersonalCrmPlugin from "./main";
import type { ContactRecord } from "./types";

export class NewContactModal extends Modal {
  private name = "";
  constructor(app: App, private plugin: PersonalCrmPlugin) { super(app); }
  onOpen(): void { this.modalEl.addClass("personal-crm-modal"); this.contentEl.empty(); this.setTitle("New contact"); new Setting(this.contentEl).setName("Name").addText(t => t.onChange(v => this.name = v)); new Setting(this.contentEl).setName("Privacy").setDesc("This creates an Obsidian workspace note only. It never creates or removes an iCloud contact."); new Setting(this.contentEl).addButton(b => b.setButtonText("Save").setCta().onClick(async () => { if (!this.name.trim()) { new Notice("Name is required."); return; } await this.plugin.repository.createLocalContact(this.name); new Notice("Local CRM workspace created."); this.close(); await this.plugin.refreshViews(); })).addButton(b => b.setButtonText("Cancel").onClick(() => this.close())); }
}

export class ContactDetailModal extends Modal {
  constructor(app: App, private plugin: PersonalCrmPlugin, private contact: ContactRecord) { super(app); }
  onOpen(): void { this.modalEl.addClass("personal-crm-modal"); this.contentEl.empty(); this.setTitle(this.contact.displayName); const summary = this.contentEl.createDiv("personal-crm-detail-summary"); summary.createEl("span", { text: this.contact.syncState, cls: `personal-crm-chip is-${this.contact.syncState}` }); summary.createEl("span", { text: this.contact.recordState }); const details = this.contentEl.createDiv("personal-crm-detail-fields"); [["Email", this.contact.emails.join(", ")], ["Phone", this.contact.phones.join(", ")], ["Relationship", this.contact.relationshipType], ["Church", this.contact.church], ["Status", this.contact.status], ["Cadence", this.contact.cadenceDays ? `Every ${this.contact.cadenceDays} days` : ""], ["Preferred contact", [this.contact.preferredContactMethod, this.contact.preferredContactTime].filter(Boolean).join(" · ")], ["Tags", this.contact.tags.join(", ")], ["Family", (this.contact.familyMembers ?? []).join(", ")], ["Anniversary", this.contact.anniversary ?? ""]].forEach(([label, value]) => { if (value) { const row = details.createDiv("personal-crm-detail-row"); row.createEl("strong", { text: `${label}:` }); row.createEl("span", { text: value }); } }); this.contentEl.createEl("h3", { text: "iCloud Notes" }); this.contentEl.createEl("pre", { text: this.contact.notes || "No iCloud Notes content" }); new Setting(this.contentEl).addButton(b => b.setButtonText("Open note").onClick(() => { const file = this.plugin.app.vault.getAbstractFileByPath(this.contact.path); if (file instanceof TFile) void this.plugin.app.workspace.getLeaf(true).openFile(file); this.close(); })).addButton(b => b.setButtonText("Close").onClick(() => this.close())); }
}
