import { App, TFile, TFolder, normalizePath } from "obsidian";
import { fetchResources, parseContactGroups, parseVCard } from "./carddav";
import type { ContactRecord, ContactSettings, SyncResult } from "./types";
import { cleanPath, isoNow, listValue, normalizeValue, safeName, today, yamlQuote } from "./utils";
const START = "<!-- red-beard:personal-crm:start -->"; const END = "<!-- red-beard:personal-crm:end -->";
function legacyCrmFields(notes: string): { relationshipType: string; status: string; church: string; cadenceDays: number | null; tags: string[]; preferredContactMethod: string; preferredContactTime: string; familyMembers: string[]; socialProfiles: string[]; instantMessageHandles: string[]; anniversary: string } {
  const match = notes.match(/---\s*REDOS CRM START\s*---([\s\S]*?)---\s*REDOS CRM END\s*---/i);
  if (!match) return { relationshipType: "", status: "", church: "", cadenceDays: null, tags: [], preferredContactMethod: "", preferredContactTime: "", familyMembers: [], socialProfiles: [], instantMessageHandles: [], anniversary: "" };
  const value = (label: string) => (match[1].match(new RegExp(`^${label}:\\s*(.*)$`, "im"))?.[1] ?? "").trim();
  const cadence = Number(value("Cadence Days"));
  const list = (label: string) => value(label).split(/[,;|]/).map(item => item.trim()).filter(Boolean);
  return { relationshipType: value("Relationship Type"), status: value("Status"), church: value("Church"), cadenceDays: Number.isFinite(cadence) && cadence > 0 ? cadence : null, tags: list("Tags"), preferredContactMethod: value("Preferred Contact Method"), preferredContactTime: value("Preferred Contact Time"), familyMembers: list("Family Members"), socialProfiles: list("Social Profiles"), instantMessageHandles: list("Instant Message Handles"), anniversary: value("Anniversary") };
}

export class ContactRepository {
  constructor(private app: App, private settings: ContactSettings) {}
  updateSettings(settings: ContactSettings): void { this.settings = settings; }
  get root(): string { return cleanPath(this.settings.rootFolder, "Collections/Personal CRM"); }
  private files(): TFile[] { return this.app.vault.getMarkdownFiles().filter(file => file.path.startsWith(`${cleanPath(this.settings.contactsFolder, `${this.root}/Contacts`)}/`)); }
  private fm(file: TFile): Record<string, unknown> { return this.app.metadataCache.getFileCache(file)?.frontmatter ?? {}; }
  getContacts(): ContactRecord[] { return this.files().map(file => this.fromFile(file)).filter(Boolean).sort((a, b) => a.displayName.localeCompare(b.displayName)); }
  private fromFile(file: TFile): ContactRecord { const f = this.fm(file); const notes = String(f.icloud_notes ?? ""); const legacy = legacyCrmFields(notes); return { id: String(f.contact_id ?? f.id ?? file.basename), displayName: String(f.display_name ?? f.name ?? file.basename), givenName: String(f.given_name ?? ""), familyName: String(f.family_name ?? ""), emails: listValue(f.emails), phones: listValue(f.phones), organization: String(f.organization ?? ""), addresses: listValue(f.addresses), websites: listValue(f.websites), birthday: String(f.birthday ?? ""), notes, icloudUid: String(f.icloud_uid ?? ""), href: String(f.icloud_href ?? ""), etag: String(f.icloud_etag ?? ""), syncState: (String(f.sync_state ?? "new-in-icloud") as ContactRecord["syncState"]), recordState: String(f.record_state ?? "active") === "inactive" ? "inactive" : "active", relationshipType: String(f.relationship_type ?? legacy.relationshipType), status: String(f.status ?? legacy.status), church: String(f.church ?? legacy.church), tags: listValue(f.tags).length ? listValue(f.tags) : legacy.tags, prayerEnabled: f.prayer_enabled === true || String(f.prayer_enabled).toLowerCase() === "true", prayerCategories: listValue(f.prayer_categories), cadenceDays: f.cadence_days == null || f.cadence_days === "" ? legacy.cadenceDays : Number(f.cadence_days), preferredContactMethod: String(f.preferred_contact_method ?? legacy.preferredContactMethod), preferredContactTime: String(f.preferred_contact_time ?? legacy.preferredContactTime), familyMembers: listValue(f.family_members).length ? listValue(f.family_members) : legacy.familyMembers, socialProfiles: listValue(f.social_profiles).length ? listValue(f.social_profiles) : legacy.socialProfiles, instantMessageHandles: listValue(f.instant_message_handles).length ? listValue(f.instant_message_handles) : legacy.instantMessageHandles, anniversary: String(f.anniversary ?? legacy.anniversary), nextContactAt: String(f.next_contact_at ?? ""), path: file.path }; }
  async initialize(): Promise<void> { for (const folder of [this.root, this.settings.contactsFolder, this.settings.householdsFolder, this.settings.interactionsFolder, this.settings.reportsFolder, this.settings.syncFolder]) await this.ensureFolder(folder); }
  private async ensureFolder(path: string): Promise<void> { const normalized = normalizePath(path); const existing = this.app.vault.getAbstractFileByPath(normalized); if (existing instanceof TFolder) return; if (existing) throw new Error(`A file already exists at ${normalized}`); const parent = normalized.slice(0, normalized.lastIndexOf("/")); if (parent) await this.ensureFolder(parent); await this.app.vault.createFolder(normalized); }
  async createLocalContact(displayName: string): Promise<TFile> { await this.initialize(); const id = `CRM-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; const path = normalizePath(`${cleanPath(this.settings.contactsFolder, `${this.root}/Contacts`)}/${safeName(displayName)}.md`); const unique = this.app.vault.getAbstractFileByPath(path) ? `${path.replace(/\.md$/, "")} ${Date.now()}.md` : path; return this.app.vault.create(unique, this.note({ id, displayName, syncState: "changed-locally", recordState: "active", icloudUid: "", href: "", etag: "", givenName: "", familyName: "", emails: [], phones: [], organization: "", addresses: [], websites: [], birthday: "", notes: "", relationshipType: "", status: "", church: "", tags: [], prayerEnabled: false, prayerCategories: [], cadenceDays: null, nextContactAt: "", path: unique })); }
  private managedBlock(c: Partial<ContactRecord> & { displayName: string }): string { return [START, "## iCloud snapshot", "", `- Name: ${c.displayName}`, `- Email: ${(c.emails ?? []).join(", ") || "None"}`, `- Phone: ${(c.phones ?? []).join(", ") || "None"}`, `- Organization: ${c.organization || "None"}`, `- Birthday: ${c.birthday || "None"}`, `- Sync state: ${c.syncState ?? "changed-locally"}`, "", "### iCloud Notes", "", c.notes || "_No iCloud Notes content._", END].join("\n"); }
  private replaceManagedBlock(content: string, block: string): string { const start = content.indexOf(START); const end = content.indexOf(END); if (start >= 0 && end > start) return `${content.slice(0, start)}${block}${content.slice(end + END.length)}`; const anchor = content.indexOf("\n## Relationship notes"); return anchor >= 0 ? `${content.slice(0, anchor)}\n\n${block}${content.slice(anchor)}` : `${content.trimEnd()}\n\n${block}\n`; }
  private note(c: Partial<ContactRecord> & { id: string; displayName: string }): string { const now = isoNow(); return ["---", "type: personal-crm-contact", "schema_version: 1", `contact_id: ${yamlQuote(c.id)}`, `display_name: ${yamlQuote(c.displayName)}`, `given_name: ${yamlQuote(c.givenName ?? "")}`, `family_name: ${yamlQuote(c.familyName ?? "")}`, `icloud_uid: ${yamlQuote(c.icloudUid ?? "")}`, `icloud_href: ${yamlQuote(c.href ?? "")}`, `icloud_etag: ${yamlQuote(c.etag ?? "")}`, `sync_state: ${yamlQuote(c.syncState ?? "changed-locally")}`, `record_state: ${yamlQuote(c.recordState ?? "active")}`, `relationship_type: ${yamlQuote(c.relationshipType ?? "")}`, `status: ${yamlQuote(c.status ?? "")}`, `church: ${yamlQuote(c.church ?? "")}`, `preferred_contact_method: ${yamlQuote(c.preferredContactMethod ?? "")}`, `preferred_contact_time: ${yamlQuote(c.preferredContactTime ?? "")}`, `family_members: ${yamlQuote((c.familyMembers ?? []).join(", "))}`, `social_profiles: ${yamlQuote((c.socialProfiles ?? []).join(", "))}`, `instant_message_handles: ${yamlQuote((c.instantMessageHandles ?? []).join(", "))}`, `anniversary: ${yamlQuote(c.anniversary ?? "")}`, `prayer_enabled: ${c.prayerEnabled === true}`, `prayer_categories: []`, `cadence_days: ${c.cadenceDays ?? "null"}`, `next_contact_at: ${yamlQuote(c.nextContactAt ?? "")}`, `created: ${yamlQuote(now)}`, `updated: ${yamlQuote(now)}`, "---", "", `# ${c.displayName}`, "", this.managedBlock(c), "", "## Relationship notes", "", "## Interactions", "", "## Follow-ups", ""].join("\n"); }
  async syncReadOnly(): Promise<SyncResult> { await this.initialize(); const resources = await fetchResources(this.settings); const groups = parseContactGroups(resources); const selectedNames = new Set(this.settings.selectedGroupNames.map(value => normalizeValue(value))); const allowedUids = selectedNames.size ? new Set(groups.filter(group => selectedNames.has(normalizeValue(group.name))).flatMap(group => group.memberUids)) : null; const existing = this.getContacts(); const byUid = new Map(existing.filter(c => c.icloudUid).map(c => [c.icloudUid, c])); let imported = 0, updated = 0, conflicts = 0, failed = 0; const seen = new Set<string>(); for (const resource of resources) { try { const card = parseVCard(resource.vcardText); if (card.kind.toLowerCase() === "group" || (allowedUids && !allowedUids.has(card.uid))) continue; const match = byUid.get(card.uid); seen.add(match?.id ?? card.uid); if (match) { if (match.etag && match.etag !== resource.etag) { await this.updateFromCard(match, card, resource.href, resource.etag, "changed-in-icloud"); updated++; } } else { const candidate = existing.find(c => !c.icloudUid && (normalizeValue(c.displayName) === normalizeValue(card.displayName) || c.emails.some(e => card.emails.includes(e)))); if (candidate) { conflicts++; await this.updateFromCard(candidate, card, resource.href, resource.etag, "conflict"); } else { await this.importCard(card, resource); imported++; } } } catch { failed++; } } let missing = 0; for (const contact of existing.filter(c => c.icloudUid && c.recordState === "active")) { if (!seen.has(contact.id) && !seen.has(contact.icloudUid)) { await this.setState(contact, "missing-remotely"); missing++; } } await this.writeSyncJournal({ imported, updated, conflicts, missing, failed, addressBooks: [] }); return { imported, updated, conflicts, missing, failed, addressBooks: [] }; }
  private async importCard(card: ReturnType<typeof parseVCard>, resource: { href: string; etag: string }): Promise<void> { const folder = cleanPath(this.settings.contactsFolder, `${this.root}/Contacts`); const base = normalizePath(`${folder}/${safeName(card.displayName)}.md`); let path = base; let index = 2; while (this.app.vault.getAbstractFileByPath(path)) path = normalizePath(`${folder}/${safeName(card.displayName)} ${index++}.md`); const legacy = legacyCrmFields(card.notes); await this.app.vault.create(path, this.note({ id: `CRM-${Math.random().toString(36).slice(2, 8).toUpperCase()}`, displayName: card.displayName, givenName: card.givenName, familyName: card.familyName, emails: card.emails, phones: card.phones, organization: card.organization, addresses: card.addresses, websites: card.websites, birthday: card.birthday, notes: card.notes, icloudUid: card.uid, href: resource.href, etag: resource.etag, syncState: "in-sync", recordState: "active", relationshipType: legacy.relationshipType, status: legacy.status, church: legacy.church, tags: legacy.tags, preferredContactMethod: legacy.preferredContactMethod, preferredContactTime: legacy.preferredContactTime, familyMembers: legacy.familyMembers, socialProfiles: legacy.socialProfiles, instantMessageHandles: legacy.instantMessageHandles, anniversary: legacy.anniversary, prayerEnabled: false, prayerCategories: [], cadenceDays: legacy.cadenceDays, nextContactAt: "", path })); }
  private async updateFromCard(contact: ContactRecord, card: ReturnType<typeof parseVCard>, href: string, etag: string, state: ContactRecord["syncState"]): Promise<void> { const file = this.app.vault.getAbstractFileByPath(contact.path); if (!(file instanceof TFile)) return; await this.app.fileManager.processFrontMatter(file, fm => { fm.display_name = card.displayName; fm.given_name = card.givenName; fm.family_name = card.familyName; fm.emails = card.emails; fm.phones = card.phones; fm.organization = card.organization; fm.addresses = card.addresses; fm.websites = card.websites; fm.birthday = card.birthday; fm.icloud_notes = card.notes; fm.icloud_uid = card.uid; fm.icloud_href = href; fm.icloud_etag = etag; fm.sync_state = state; fm.last_synced = isoNow(); fm.updated = isoNow(); }); const current = await this.app.vault.read(file); const next = this.replaceManagedBlock(current, this.managedBlock({ displayName: card.displayName, emails: card.emails, phones: card.phones, organization: card.organization, birthday: card.birthday, notes: card.notes, syncState: state })); if (next !== current) await this.app.vault.modify(file, next); }
  private async setState(contact: ContactRecord, state: ContactRecord["syncState"]): Promise<void> { const file = this.app.vault.getAbstractFileByPath(contact.path); if (file instanceof TFile) await this.app.fileManager.processFrontMatter(file, fm => { fm.sync_state = state; fm.record_state = "inactive"; fm.updated = isoNow(); }); }
  private async writeSyncJournal(result: SyncResult): Promise<void> { const folder = cleanPath(this.settings.syncFolder, `${this.root}/Sync`); const path = normalizePath(`${folder}/${today()} - sync.json`); const content = JSON.stringify({ type: "personal-crm-sync", schema_version: 1, read_only: true, completed: isoNow(), ...result }, null, 2); const existing = this.app.vault.getAbstractFileByPath(path); if (existing instanceof TFile) await this.app.vault.modify(existing, content); else await this.app.vault.create(path, content); }
}
